//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace allseen { namespace Introspectable {

// Methods
public ref class IntrospectableGetDescriptionLanguagesCalledEventArgs sealed
{
public:
    IntrospectableGetDescriptionLanguagesCalledEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property IntrospectableGetDescriptionLanguagesResult^ Result
    {
        IntrospectableGetDescriptionLanguagesResult^ get() { return m_result; }
        void set(_In_ IntrospectableGetDescriptionLanguagesResult^ value) { m_result = value; }
    }

    Windows::Foundation::Deferral^ GetDeferral();

    static Windows::Foundation::IAsyncOperation<IntrospectableGetDescriptionLanguagesResult^>^ GetResultAsync(IntrospectableGetDescriptionLanguagesCalledEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<IntrospectableGetDescriptionLanguagesResult^>
        {
            return t;
        });
    }
    
private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<IntrospectableGetDescriptionLanguagesResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    IntrospectableGetDescriptionLanguagesResult^ m_result;
};

public ref class IntrospectableIntrospectWithDescriptionCalledEventArgs sealed
{
public:
    IntrospectableIntrospectWithDescriptionCalledEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ Platform::String^ interfaceMemberLanguageTag);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property IntrospectableIntrospectWithDescriptionResult^ Result
    {
        IntrospectableIntrospectWithDescriptionResult^ get() { return m_result; }
        void set(_In_ IntrospectableIntrospectWithDescriptionResult^ value) { m_result = value; }
    }

    property Platform::String^ LanguageTag
    {
        Platform::String^ get() { return m_interfaceMemberLanguageTag; }
    }

    Windows::Foundation::Deferral^ GetDeferral();

    static Windows::Foundation::IAsyncOperation<IntrospectableIntrospectWithDescriptionResult^>^ GetResultAsync(IntrospectableIntrospectWithDescriptionCalledEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<IntrospectableIntrospectWithDescriptionResult^>
        {
            return t;
        });
    }
    
private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<IntrospectableIntrospectWithDescriptionResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    IntrospectableIntrospectWithDescriptionResult^ m_result;
    Platform::String^ m_interfaceMemberLanguageTag;
};

// Readable Properties
// Writable Properties
} } } 
